### PR TITLE
Attachments after removing gitignore files

### PR DESCRIPTION
**Pull request by Adarshraj2401**

### CODE REVIEW

**Comment by Adarshraj2401** [comment]
after removing the .idea and .dart_tools folder There are a bunch of errors on every file. I have pushed the code with these errors.

**Comment by yashlm** [comment]
> after removing the .idea and .dart_tools folder There are a bunch of errors on every file. I have pushed the code with these errors.

can you specify what errors exactly are you encountering and what are the other changes you've done besides deleting the aforementioned folders

**Comment by Adarshraj2401** [comment]
I removed .dart_tools / .idea / .flutter_plugins / .flutter_plugin_dependencies.
I am gettin error on imports showing this 
"Target of URI doesn't exist: 'package:iitk_mail_client/EmailCache/initializeobjectbox.dart'.
Try creating the file referenced by the URI, or try using a URI for a file that does exist."
Mainly the imports are not working.

**Comment by yashlm** [comment]
> I removed .dart_tools / .idea / .flutter_plugins / .flutter_plugin_dependencies. I am gettin error on imports showing this "Target of URI doesn't exist: 'package:iitk_mail_client/EmailCache/initializeobjectbox.dart'. Try creating the file referenced by the URI, or try using a URI for a file that does exist." Mainly the imports are not working.

maybe you deleted them from your local setup as well thats why...if thats the case, build the app again to get those files back...just dont push them from next time

**Pull request merged**
