### PR TITLE
Address Book

### PR DESCRIPTION
**Pull request by Abhimanyu-dev**
Added the address book functionality which stores mail whenever you send a mail.
Also updated the Email model and fetching to store a unique ID which can be used to fetch mails on the go and will also enable us to only store the mail subject and senders and not the body.
Added refresh functionality that works for now but will need to be updated with the Email model.
Also added infinite scroll that fetches new mails as soon as you scroll to the bottom of the page.

### CODE REVIEW

**Comment by bmerchant22** [comment]
By fetching new mails in infinite scroll, you mean only the headers right?

**Comment by bmerchant22** [comment]
Also, implement the manual address book feature, such that user can view the address list and edit the address list

**Comment by Abhimanyu-dev** [comment]
> By fetching new mails in infinite scroll, you mean only the headers right?

The current mail model does not implement fetching just the headers and I did not update the code just yet but will do now

**Comment by Abhimanyu-dev** [comment]
> Also, implement the manual address book feature, such that user can view the address list and edit the address list

This will take about a day more, the mail I'll update in a few hours.

**Comment by bmerchant22** [comment]
> > By fetching new mails in infinite scroll, you mean only the headers right?
> 
> The current mail model does not implement fetching just the headers and I did not update the code just yet but will do now

Ok, so you haven't changed the cache mail model, you have just extended the fetching whenever we scroll further, right?

**Comment by Abhimanyu-dev** [comment]
> > > By fetching new mails in infinite scroll, you mean only the headers right?
> > 
> > 
> > The current mail model does not implement fetching just the headers and I did not update the code just yet but will do now
> 
> Ok, so you haven't changed the cache mail model, you have just extended the fetching whenever we scroll further, right?

I just updated one parameter, i.e. the unique ID, and create a new function that fetches mail using this ID and then ran it as you scroll down. 
Now I'm working on making the mail model such that it does not store the body but it is fetched from the server everytime you open a mail. Should I implement this or do you have any other idea of implementing this because storing body takes up a lot of storage ?

**Comment by bmerchant22** [comment]
> > > > By fetching new mails in infinite scroll, you mean only the headers right?
> > > 
> > > 
> > > The current mail model does not implement fetching just the headers and I did not update the code just yet but will do now
> > 
> > 
> > Ok, so you haven't changed the cache mail model, you have just extended the fetching whenever we scroll further, right?
> 
> I just updated one parameter, i.e. the unique ID, and create a new function that fetches mail using this ID and then ran it as you scroll down. Now I'm working on making the mail model such that it does not store the body but it is fetched from the server everytime you open a mail. Should I implement this or do you have any other idea of implementing this because storing body takes up a lot of storage ?

Don't work on the storage part, just complete the address book functionalities. Storage part is being worked upon by other team, you can see the thread for more info

**Pull request merged**
