### PR TITLE
Attachment Visibility

### PR DESCRIPTION
**Pull request by Adarshraj2401**
Attachment visible on the email_view_page. No functionality yet.

### CODE REVIEW

**Comment by bmerchant22** [comment]
Can you provide some more description for this PR, I see some files you have added just 100 lines of code commented, why??, also, is the issue of downloading attachments is resolved in this PR?

**Comment by Adarshraj2401** [comment]
Yes now the attachments are downloading. The file can be downloaded with the download button, and when the use clicks on the Attachment it opens the file for viewing and downloads it. It has been insured that multiple copies of the same file are not downloaded.

**Comment by Adarshraj2401** [comment]
Gitignore files removed from the pull request.

**Comment by bmerchant22** [comment]
Remove .dart_tool and .idea as well

**Comment by Adarshraj2401** [comment]
after deleting these two folders i am getting a lot of errors,I have to push my code with these errors?

**Pull request closed without merging**
