### PR TITLE
Auth Mechanism and Authorization order done

### PR DESCRIPTION
**Pull request by KrishJain256**
Changed the order as discussed and implemented advanced settings for auth mechanism

### CODE REVIEW

**Comment by bmerchant22** [comment]
Add and use the isLogged flag and not the username and password != null condition

**Comment by bmerchant22** [comment]
The last comment I made is not resolved yet, also don't push the .dart_tool and .idea directories and other generated files

**Comment by KrishJain256** [comment]
Yeah, almost done, I'm resolving one issue, it actually gave an error

**Comment by KrishJain256** [comment]
@bmerchant22 i have added the isLogged functionality to it and it works fine, also deleted the unnecessary files

**Comment by bmerchant22** [comment]
Also, delete the .dart_tool, .flutter plugins and dependencies, please view the .gitignore file

**Comment by KrishJain256** [comment]
@bmerchant22 oh sorry, done now, it shows its able to merge with base branch

**Comment by bmerchant22** [comment]
Also, when a person logs out, set the isLogged flag to false

**Comment by KrishJain256** [comment]
It becomes null, I had tried that yesterday, it works perfectly fine without issues
The logout button will delete all the things in the secure storage

**Pull request merged**
